version: '3.9'

services:
  app:
    build: .                        
    image: pruebafastapi-app        
    container_name: python_container
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENV=development
    command: uvicorn main:app --host 0.0.0.0 --port 8000
